### ISSUE TITLE
Error using CUDA

### ISSUE THREAD

**Issue by rsteca** [Seanny123/da-rnn#10]
I get this error when trying to use the code with GPU (it works fine with CPU):

```2019-05-14 19:51:48,049 - VOC_TOPICS - INFO - Using computation device: cuda:0
2019-05-14 19:51:48,675 - VOC_TOPICS - INFO - Shape of data: (40560, 82).
Missing in data: 0.
2019-05-14 19:51:48,785 - VOC_TOPICS - INFO - Training size: 28392.
2019-05-14 19:51:51,329 - VOC_TOPICS - INFO - Iterations per epoch: 221.812 ~ 222.
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    iter_loss, epoch_loss = train(model, data, config, n_epochs=10, save_plots=save_plots)
  File "main.py", line 84, in train
    loss = train_iteration(net, t_cfg.loss_func, feats, y_history, y_target)
  File "main.py", line 143, in train_iteration
    input_weighted, input_encoded = t_net.encoder(numpy_to_tvar(X))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/da-rnn/da-rnn/modules.py", line 43, in forward
    input_data.permute(0, 2, 1)), dim=2)  # batch_size * input_size * (2*hidden_size + T - 1)
RuntimeError: Expected object of backend CPU but got backend CUDA for sequence element 2 in sequence argument at position #1 'tensors'```

**Comment by ywatanabe1989** [comment]
Me too.

**Comment by wxjeacen** [comment]
Me tooo

**Comment by barryflower** [comment]
Yes, the same problem.  Has this been tested with cuda?

**Comment by barryflower** [comment]
Further to this problem there is an easy fix.  I have reproduce the git diff of module.py below.  If you add these few changes then CUDA works. BAsically you need to explicit send data to CUDA and there was a couple of places it was missing.

> git diff modules.py
diff --git a/modules.py b/modules.py
index 768bb7e..99748ab 100644
--- a/modules.py
+++ b/modules.py
@@ -2,14 +2,14 @@ import torch
 from torch import nn
 from torch.autograd import Variable
 from torch.nn import functional as tf
-
+from constants import device    #   Fixed CUDA bug  #

 def init_hidden(x, hidden_size: int):
     """
     Train the initial value of the hidden state:
     https://r2rt.com/non-zero-initial-states-for-recurrent-neural-networks.html
     """
-    return Variable(torch.zeros(1, x.size(0), hidden_size))
+    return Variable(torch.zeros(1, x.size(0), hidden_size).to(device))   #   Fixed CUDA bug  #


 class Encoder(nn.Module):
@@ -57,7 +57,7 @@ class Encoder(nn.Module):
             input_weighted[:, t, :] = weighted_input
             input_encoded[:, t, :] = hidden

-        return input_weighted, input_encoded
+        return input_weighted, input_encoded.to(device) # Fixed CUDA bug #


 class Decoder(nn.Module):
